### ISSUE TITLE
The description bar on the Pokecard generator should be left aligned and use the entire hortizontal space

### ISSUE THREAD

**Issue by Dadisaa** [lvandernoll/pokecardmaker.net#348]
**The description bar on the Pokecard generator should be left aligned and use the entire hortizontal space - the current (default) placement looks odd from a alignment perspective**
...

**Screenshots**
...
![WhatsApp Image 2023-01-19 at 00 12 38](https://user-images.githubusercontent.com/123014703/213267138-fc31859e-60eb-48aa-a6e3-7649063f4932.jpg)

**Comment by qwertyuiop265000** [comment]
There should be an option for right aligned or centered text.

**Comment by lvandernoll** [comment]
The entire horizontal width should not be used. That would mean the description can overlap the illustrator and set icons.
Here are some examples I used as reference:
SWSH set cards have the dex entry horizontally aligned on the right, and vertically in the center. It takes up around 58% of the card width.
![image](https://user-images.githubusercontent.com/36536517/213434553-bc3034f4-9ab5-4f95-80a3-2c0da2ca60be.png)
SM set cards have the text aligned horizontally on the left, with a 48% width:
![image](https://user-images.githubusercontent.com/36536517/213435241-77349db8-b3f4-4888-add0-6c4b5c48370f.png)

I believe the current implementation is correct so I'm closing this issue but if you feel otherwise, feel free to re-open it!

**Comment by qwertyuiop265000** [comment]
👍
